# Generated by Django 6.0.3 on 2026-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="time_limit",
            field=models.IntegerField(default=60, help_text="Time limit in seconds"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studysession",
            name="time_taken",
            field=models.IntegerField(
                default=0, help_text="Actual time taken in seconds"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studysession",
            name="timed_out",
            field=models.BooleanField(default=False),
        ),
    ]
