# Generated by Django 6.0.3 on 2026-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_session", "0003_alter_studysession_time_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="time_limit",
            field=models.IntegerField(default=0, help_text="Time limit in seconds"),
        ),
    ]
