# Generated by Django 5.2 on 2026-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_session", "0004_alter_studysession_time_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
