# Generated by Django 6.0.3 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
